# This is template data, available in templates like FONT_DIR={{ .fontDir }}

fontsDir: .local/share/fonts

terminalFont:
  fileName: Fira Code Regular Nerd Font Complete Mono.ttf
  name: FiraCode Nerd Font Mono
